apiVersion: v1
kind: Service
metadata:
  name: nginx-port
  labels:
    name: nginx-port
  namespace: exquisapp  
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30700
    name: nginx-home
    targetPort: 80
  selector:
    app: nginx      
